language: objective-c
osx_image: xcode7
xcode_workspace: App/AheuiSwift.xcodeproj/project.xcworkspace
xcode_scheme: AheuiSwift
xcode_sdk: iphonesimulator
before_install:
  - sudo gem install xcpretty
script:
  - xcodebuild -version
  - xcodebuild --help
  - xcodebuild test \
      -project App/AheuiSwift.xcodeproj \
      -scheme AheuiSwift \
      -sdk iphonesimulator \
      | xcpretty -c
notifications:
  email: false
