language: objective-c
osx_image: xcode7
xcode_workspace: App/AheuiSwift.xcodeproj/project.xcworkspace
xcode_scheme: AheuiSwift
xcode_sdk: iphonesimulator
before_install:
  - xcodebuild -version
  - sudo gem install xcpretty
script:
  - xcodebuild test -workspace App/AheuiSwift.xcodeproj/project.xcworkspace -scheme AheuiSwift -sdk iphonesimulator | xcpretty -c
notifications:
  email: false
